### ISSUE TITLE
Database Issue

### ISSUE THREAD

**Issue by iqbalnurhabib** [tmijail/Odoo-Power-BI-Connector#22]
hello tmijail
database can't connect, looks like an error occurred in res.user.parent_id

![datbase error](https://github.com/tmijail/Odoo-Power-BI-Connector/assets/49646304/adaa3838-aeaa-48c1-bd3e-5c791be9c6e5)
![datbase error 2](https://github.com/tmijail/Odoo-Power-BI-Connector/assets/49646304/87c1dc9f-5c57-401e-ae8c-d5aab870c4bb)

Odoo Server Error: Invalid parent field: res.users.parent_id
Details:
    Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/16.0/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/16.0/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/16.0/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/16.0/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/custom/trial/saas_trial/controllers/main.py", line 275, in jsonrpc
    res = super(OdooRPC, self).jsonrpc(service, method, args)
  File "/home/odoo/src/odoo/16.0/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/16.0/odoo/addons/base/controllers/rpc.py", line 156, in jsonrpc
    return dispatch_rpc(service, method, args)
  File "/home/odoo/src/odoo/16.0/odoo/http.py", line 366, in dispatch_rpc
    return dispatch(method, params)
  File "/home/odoo/src/odoo/16.0/odoo/service/model.py", line 37, in dispatch
    res = execute_kw(db, uid, *params[3:])
  File "/home/odoo/src/odoo/16.0/odoo/service/model.py", line 59, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File "/home/odoo/src/odoo/16.0/odoo/service/model.py", line 65, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/home/odoo/src/odoo/16.0/odoo/service/model.py", line 50, in execute_cr
    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)
  File "/home/odoo/src/odoo/16.0/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/16.0/odoo/api.py", line 457, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/16.0/odoo/api.py", line 430, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 2188, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 2213, in _read_group_raw
    query = self._where_calc(domain)
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 4407, in _where_calc
    return expression.expression(domain, self).query
  File "/home/odoo/src/odoo/16.0/odoo/osv/expression.py", line 447, in __init__
    self.parse()
  File "/home/odoo/src/odoo/16.0/odoo/osv/expression.py", line 721, in parse
    right_ids = comodel.with_context(active_test=False)._search([(path[1], operator, right)], order='id')
  File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/res_users.py", line 208, in _search
    return super(Groups, self)._search(args, offset=offset, limit=limit, order=order, count=count, access_rights_uid=access_rights_uid)
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 4639, in _search
    query = self._where_calc(domain)
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 4407, in _where_calc
    return expression.expression(domain, self).query
  File "/home/odoo/src/odoo/16.0/odoo/osv/expression.py", line 447, in __init__
    self.parse()
  File "/home/odoo/src/odoo/16.0/odoo/osv/expression.py", line 829, in parse
    domain = HIERARCHY_FUNCS[operator]('id', ids2, comodel)
  File "/home/odoo/src/odoo/16.0/odoo/osv/expression.py", line 561, in child_of_domain
    raise ValueError(f"Invalid parent field: {left_model._fields[parent_name]}")
ValueError: Invalid parent field: res.users.parent_id

Regards,

**Comment by tmijail** [comment]
Fixed in [v0.2.0](https://github.com/tmijail/Odoo-Power-BI-Connector/releases/tag/v0.2.0)
